name: Terraform CI/CD Local com Secrets

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: Terraform Plan e Apply (Local)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Preparar arquivos sensíveis
        run: |
          mkdir -p ./security
          printf "%s\n" "${{ secrets.TF_VARS_CONTENT }}" > terraform.tfvars
          printf "%s\n" "${{ secrets.ENV_FILE_CONTENT }}" > ./security/.env
          printf "%s\n" "${{ secrets.DATASOURCES_FILE }}" > ./security/datasources.yml
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ./security/tf-proxmox_id_rsa

      - name: Ajustar permissões da chave privada
        run: chmod 600 ./security/tf-proxmox_id_rsa

      - name: Inicializar Terraform (local)
        run: terraform init

      - name: Validar sintaxe do Terraform
        run: terraform validate

      - name: Verificar plano de execução
        run: terraform plan -out=plano-grafana

      #- name: Aplicar infraestrutura (somente na branch main)
      #  if: github.ref == 'refs/heads/main'
      #  run: terraform apply -auto-approve plano-grafana
