name: Terraform CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]


jobs:
  debug-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar dig e nslookup
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      - name: Testar resolução DNS do domínio
        run: |
          echo "🔎 Testando DNS:"
          dig ci-proxmox.mcn.tec.br
          nslookup ci-proxmox.mcn.tec.br

  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar formatação do Terraform
        run: terraform fmt -check -recursive

      - name: Validar sintaxe do Terraform
        run: terraform validate

      - name: Verificar plano de execução
        run: terraform plan
