name: Terraform CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar formatação do Terraform
        run: terraform fmt -check -recursive

      - name: Validar sintaxe do Terraform
        run: terraform validate

      - name: Verificar plano de execução
        run: terraform plan
